### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by zbqiao** [platformio/platformio-core-installer#103]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.0
  PIO IDE: v2.0.1
  System: Darwin, 19.6.0, x64

  %23 Exception
  ```
  Error:     ERROR: Command errored out with exit status 1:
     command: /Users/qzb/.platformio/penv/bin/python -c 'import sys, setuptools, tokenize

**Comment by ivankravets** [comment]
Could you run this command in the terminal and restart VSCode?
```
rm -rf /Users/qzb/.platformio/penv
```
