### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by AnatoliiBeep** [platformio/platformio-core-installer#1363]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Linux, 4.15.0-142-generic, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/home/a1/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "/home/a1/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "/home/a1/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 45, in bootstrap
    import pioinstaller.__main__
zipimport.ZipImportError: can't decompress data

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
