### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by NguyenHuy-0512** [platformio/platformio-core-installer#1496]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: Error: Could not find compatible Python 3.6 or above in your system.Please install the latest official Python 3 and restart installation:
https://docs.platformio.org/page/faq.html%23install-python-interpreter
 -> Installer version: 1.0.3
Platform: Windows-10
Python version: 3.9.7 (default, Sep 23 2021, 09:13:41)  [GCC 10.3.0 64 bit (AMD64)]
Python path: C:\msys64\mingw64\bin\python.exe
Creating a virtual environment at C:\Users\LAPTOP D

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
