### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by pottendo** [platformio/platformio-core-installer#1776]
Hi,

below the output when launching VSCode + platformio addon.
My system: Ubuntu 20.04, latest updates.
I've used VSCode and platformio heavily before on this machine, but after the latest updates, VSCode + pio failed to start, as it could recreate the penv. 

So I've tried to install the penv by hand (without vscode, etc.), cleaned .platformio before, by using the commands:
$ python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
Installer version: 1.0.3
Platform: Linux-5.11.0-39-generic-x86_64-with-glibc2.33
Python version: 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/pottendo/.platformio/penv
/usr/bin/python3
Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
Traceback (most recent call last):
  File "<string>", line 105, in <module>
  File "<string>", line 101, in main
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/tmp/tmpp_zbtz_d']' returned non-zero exit status 1.

Unfortunately the installer is not very verbose about the reason, why the creation failed.
I tried to remove all artifacts of previous installations as good as I can:
  - .platformio
  - .vscode
Ubuntu pio packages (sudo apt remove platformio)

Here the strace output of running the script get-platformio.py by hand:
  https://pastebin.com/zayhJ2XV
(note that I've stripped out the quite long middle part - in case of need I can provide the full log)

thx for any support!

%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Linux, 5.11.0-39-generic, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.0.3
Platform: Linux-5.11.0-39-generic-x86_64-with-glibc2.33
Python version: 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/pottendo/.platformio/penv
/usr/bin/python3

	at /opt/home/pottendo/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:769806
	at ChildProcess.a (/opt/home/pottendo/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:771396)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at Pipe.<anonymous> (net.js:673:12)
  ```

**Comment by ivankravets** [comment]
See the solution in https://github.com/platformio/platformio-core-installer/issues/1774
