### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by DanHarrison303** [platformio/platformio-core-installer#1820]
Stuck in infinite loop with installer failing to recognize Python install that I just did.  Restarted computer and started Python just to be sure it was properly  and completely installed, and the Platfomio installer still refused to acknowledge it.  I select that I have Python already installed and navigate to the folder and it still fails to move forward and continues to ask if I have it or want to install it.

Error: Can not find Python Interpreter. Please install Python 3.5 or above manually at t.value (C:\Users\Dan.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:30165) at t.value (C:\Users\Dan.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:27975) at async Promise.all (index 3)

**Comment by ivankravets** [comment]
PlatformIO IDE extension for Atom is outdated. Please use https://platformio.org/install/ide?install=vscode
