### ISSUE TITLE
Cannot install platformio on Windows 11

### ISSUE THREAD

**Issue by offspringer** [platformio/platformio-core-installer#1823]
%23 Description of problem
Cannot install platformio, regardless of method. Visual Studio Code also fails while creating virtual environment and pip install platformio fails on setup.py with message "ModuleNotFoundError: No module named 'platformio'".

%23 Configuration

OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
System Type:              x64-based PC
Python version:          3.9.8 
pip version:                21.3.1

%23 Exception

`D:\Desktop>python get-platformio.py
Installer version: 1.1.0
Platform: Windows-10
Python version: 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)]
Python path: D:\Workspace\SDKs\python-3.9.8-embed-amd64\python.exe
Creating a virtual environment at C:\Users\Roger\.platformio\penv
D:\Workspace\SDKs\python-3.9.8-embed-amd64\python.exe
Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues`

**Comment by jwjames83** [comment]
I ran into the same error. I deleted C:\Users\<username>\.platformio - this worked me.
