### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by joelden** [platformio/platformio-core-installer#193]
Installing PlatformIO IDE...
It may take a few minutes depending on your connection speed
Please do not close this window and do not open other folders until this process is completed.

Debugging information is available via VSCode > Help > Toggle Developer Tools > Console.
Failed to install PlatformIO IDE.

%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.3
  PIO IDE: v2.1.0
  System: Windows_NT, 10.0.18363, x64

  %23 Exception
  ```
  Error: ENOENT: no such file or directory, unlink 'C:\Users\joeld\.platformio\.cache\tmp\core-dump-67036.json'
  ```

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core-installer/issues/192
