### ISSUE TITLE
requests again for python, but python is installed. Atom doesn't accept python path

### ISSUE THREAD

**Issue by p3moto** [platformio/platformio-core-installer#1967]
> Error: Can not find Python Interpreter. Please install Python 3.5 or above manually at t.value (C:\Users\andre.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:30165) at t.value (C:\Users\andre.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:27975) at async Promise.all (index 3)

but python is installed -.-
path is:
`C:\Users\andre\AppData\Local\Programs\Python\Python310`
bit if i set the path in atom, atom does not accept it -.- an requests again for python.

(also tried with python 3.9, but same shit.)

when i close atom and start it again, this occurs:

> Error: Traceback (most recent call last): File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\pioinstaller\python.py", line 170, in find_compatible_pythons File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['C:\Users\andre\AppData\Local\Microsoft\WindowsApps\python3.exe', 'C:\Users\andre\.platformio\.cache\tmp\get-platformio-0.3.5.py', '--no-shutdown-piohome', 'check', 'python']' returned non-zero exit status 9009.

During handling of the above exception, another exception occurred:

> Traceback (most recent call last): File "C:\Users\andre.platformio.cache\tmp\get-platformio-0.3.5.py", line 69, in main() File "C:\Users\andre.platformio.cache\tmp\get-platformio-0.3.5.py", line 61, in main bootstrap() File "C:\Users\andre.platformio.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap pioinstaller.main.main() File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\pioinstaller__main__.py", line 122, in main File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\click\core.py", line 829, in call File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\click\core.py", line 782, in main File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\click\core.py", line 1236, in invoke File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\click\core.py", line 1066, in invoke File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\click\core.py", line 610, in invoke File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\click\decorators.py", line 21, in new_func File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\pioinstaller__main__.py", line 52, in cli File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\pioinstaller\penv.py", line 52, in create_core_penv File "C:\Users\andre.platformio.cache\tmp.piocore-installer-h234sj72\tmp2_a5coce\pioinstaller.zip\pioinstaller\python.py", line 191, in find_compatible_pythons UnboundLocalError: local variable 'error' referenced before assignment -> Installer version: 0.3.5 Platform: Windows-10 Python version: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] Python path: C:\Users\andre\AppData\Local\Programs\Python\Python310\python.exe Creating a virtual environment at C:\Users\andre.platformio\penv

> at C:\Users\andre\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5004
> at ChildProcess.s (C:\Users\andre\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4900)
> at ChildProcess.emit (events.js:223:5)
> at ChildProcess.cp.emit (C:\Users\andre\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
> at maybeClose (internal/child_process.js:1021:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

can anybody tell me what to do?

**Comment by ivankravets** [comment]
Oh, our Atom extension is outdated, maybe it makes sense to archive it. We recommend PlatformIO IDE for VSCode.
