### ISSUE TITLE
Gitpod error in installing

### ISSUE THREAD

**Issue by escapeoneone** [platformio/platformio-core-installer#209]
###### I not know English language ######
# Installing platform-vscode-ide 

I installing platformio-vscode-ide in gitpod from vsix file.
And getting error:<br>
Screenshot:
![report](https://user-images.githubusercontent.com/54133395/96288777-a16e7000-0fec-11eb-8a81-b547de4d44a9.png)

---
Text version:
###### ![icon](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/OOjs_UI_icon_error-destructive.svg/20px-OOjs_UI_icon_error-destructive.svg.png) Error: Compatible PlatformIO Core not found. <br>Reason: PlatformIO executable not found in `/home/gitpod/.platformio/penv/bin` at c (/{pathtoplatformioextension}/node_modules/platformio-node-helpers/dist/index.js:1:4911) at ChildProcess.s (/{pathtoplatformioextension}/node_modules/platformio-node-helpers/dist/index.js:1:4807) at ChildProcess.emit (events.js:189:13) at maybeClose (internal/child_process.js:970:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

_Report:
```# Description of problem  Leave a comment...  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN  - https://github.com/platformio/platformio-vscode-ide/issues?q=is:issue   # Configuration  VSCode: 1.44.0  PIO IDE: v2.1.0  System: Linux, 4.14.174 , x64  # Exception  Error: Error: Compatible PlatformIO Core not found.Reason: PlatformIO executable not found in `/home/gitpod/.platformio/penv/bin`    at c (/tmp/vscode-extensions/platformio.platformio-ide@2.1.0/extension/node_modules/platformio-node-helpers/dist/index.js:1:4911)    at ChildProcess.s (/tmp/vscode-extensions/platformio.platformio-ide@2.1.0/extension/node_modules/platformio-node-helpers/dist/index.js:1:4807)    at ChildProcess.emit (events.js:189:13)    at maybeClose (internal/child_process.js:970:16)    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)  ```_ 

##### Error icon from wikipedia.org uploaded by Iniquity

**Comment by ivankravets** [comment]
What is it?

**Comment by boomik305** [comment]
This report generated PlatformIO installer.
Screenshot

![report](https://user-images.githubusercontent.com/54133395/96288581-4dfc2200-0fec-11eb-97e9-9a5c60233d83.png)
