### ISSUE TITLE
ERROR Installin platformio extension

### ISSUE THREAD

**Issue by EmiliEced** [platformio/platformio-core-installer#2282]
This error happends on a cleaned environment.

ERROR: Command errored out with exit status 1: /home/emili/.platformio/penv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/emili/.platformio/.cache/tmp/.piocore-installer-1nelbceb/pip-install-sokdz5p2/platformio_3563d679997b4523aa901dd5167e33c6/setup.py'"'"'; __file__='"'"'/home/emili/.platformio/.cache/tmp/.piocore-installer-1nelbceb/pip-install-sokdz5p2/platformio_3563d679997b4523aa901dd5167e33c6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /home/emili/.platformio/.cache/tmp/.piocore-installer-1nelbceb/pip-record-pwwhoywz/install-record.txt --single-version-externally-managed --compile --install-headers /home/emili/.platformio/penv/include/site/python3.9/platformio Check the logs for full command output.
Error: Could not install PlatformIO Core: Command '['/home/emili/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.

 -> Installer version: 1.1.2
Platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.34
Python version: 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0]
Python path: /usr/bin/python3

**Comment by ivankravets** [comment]
Could you reproduce this issue after restarting VSCode?
