### ISSUE TITLE
AMD64 MSC v.1929 64 bit

### ISSUE THREAD

**Issue by domsobota** [platformio/platformio-core-installer#2283]
I am using Windows 11 not sure if that helps.

Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\domso\.platformio\penv\Scripts\python.exe
Creating a virtual environment at C:\Users\$USER\.platformio\penv
C:\Users\$USER\.platformio\penv\Scripts\python.exe
Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues

**Comment by ivankravets** [comment]
Could you reproduce this issue after restarting VSCode?
