### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by zeeeeeeeeeeeoo** [platformio/platformio-core-installer#2325]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.69.2
  PIO IDE: v2.5.1
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\ZE\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\ZE\.platformio\penv

	at c:\Users\ZE\.vscode\extensions\platformio.platformio-ide-2.5.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5308
	at ChildProcess.o (c:\Users\ZE\.vscode\extensions\platformio.platformio-ide-2.5.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4691)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by ivankravets** [comment]
Could you reproduce this issue after restarting VSCode?

**Comment by BlackTentacle** [comment]
I just wanted to mention that I've got the same error (under Linux, however). And yet, persists even after restarting VSCode. It also persists after removing the ~/.platformio folder

**Comment by zeeeeeeeeeeeoo** [comment]
Restarting didnt workIt ran perfectly after&nbsp;removing the ~/.platformio folder




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ivan ***@***.***&gt;; 
发送时间: 2022年7月31日(星期天) 凌晨0:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [platformio/platformio-core-installer] Installation Manager (Issue #2325)





 
Could you reproduce this issue after restarting VSCode?

**Comment by zeeeeeeeeeeeoo** [comment]
> 

restarting didnt work
it ran perfectly after removing its folder

**Comment by ivankravets** [comment]
So, do you mean that it works now?

**Comment by zeeeeeeeeeeeoo** [comment]
> So, do you mean that it works now?

Sorry for my reckless judgment.It seems still does not work well.
But at least I can see the home page
I do not know if it is normal stucking in "project wizard" for hours after creating a project.
After hours,it hints an error,I can't creat projects sucessfully

**Comment by ivankravets** [comment]
@zeeeeeeeeeeeoo what is your board?

**Comment by ivankravets** [comment]
Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type:

```
pio pkg install -g --platform "platformio/espressif32"
```

Do you have any problems with package installation?

**Comment by zeeeeeeeeeeeoo** [comment]
> Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type:
> 
> ```
> pio pkg install -g --platform "platformio/espressif32"
> ```
> 
> Do you have any problems with package installation?
it says:
PS C:\Users\ZE> pio pkg install -g --platform "platformio/espressif32"
Platform Manager: espressif32@3.4.0 is already installed
Tool Manager: toolchain-xtensa32@2.50200.97 is already installed
Tool Manager: tool-esptoolpy@1.30100.210531 is already installed

**Comment by ivankravets** [comment]
It seems you have a slow internet connection and it stucks at installing arduino code. So, try the following:

```
pio project init -b esp32dev -d C:/Users/ZE/Downloads/testproject
```

Please create `testproject` folder in Downloads or change the path to the folder where you would like to init a new project. You will see all progress.

**Comment by zeeeeeeeeeeeoo** [comment]
> Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type:
> 
> ```
> pio pkg install -g --platform "platformio/espressif32"
> ```
> 
> Do you have any problems with package installation?

It works well now! Just after typing the first code
Thank you so much!

**Comment by ivankravets** [comment]
Could you try the following links in your browser?

1. https://dl.registry.ns2.platformio.org/tools/cb/36/aefbf6f69f5e27302916f0a1d13c03da57946e5b251be009f7cd93179d41/framework-arduinoespressif32-3.20004.0.tar.gz
2. https://hk03.layerstack.com/100MB.test

What is your download speed for 1 & 2?

**Comment by zeeeeeeeeeeeoo** [comment]
> Could you try the following links in your browser?
> 
> 1. https://dl.registry.ns2.platformio.org/tools/cb/36/aefbf6f69f5e27302916f0a1d13c03da57946e5b251be009f7cd93179d41/framework-arduinoespressif32-3.20004.0.tar.gz
> 2. https://hk03.layerstack.com/100MB.test
> 
> What is your download speed for 1 & 2?

1: 10kb/s
2: 3Mb/s

**Comment by ivankravets** [comment]
@zeeeeeeeeeeeoo do you use proxy or mobile network? We had a similar issue https://github.com/platformio/platformio-core/issues/4345

We hoped that finally fix the mirrors for Chinese users.

**Comment by zeeeeeeeeeeeoo** [comment]
> @zeeeeeeeeeeeoo do you use proxy or mobile network? We had a similar issue [platformio/platformio-core#4345](https://github.com/platformio/platformio-core/issues/4345)
> 
> We hoped that finally fix the mirrors for Chinese users.

yes,I's using a proxy .
Thank you for your efforts for Chinese users

**Comment by ivankravets** [comment]
Could you try BOTH links WITHOUT proxy? Proxy is evil.

**Comment by zeeeeeeeeeeeoo** [comment]
> Could you try BOTH links WITHOUT proxy? Proxy is evil.


At the first I used the IDMDownloader with proxy and got 
1:10kb/s
2:3Mb/s


Without IDM and proxy :
1:5Mb/s
![c27dddb80286ed1db507293ea44d33d](https://user-images.githubusercontent.com/97492868/182136194-eafb3dcb-930f-4201-a340-fcb4120bd6fa.png)
2:5Mb/s
![5aa495fbf443129a1e0500357f6555b](https://user-images.githubusercontent.com/97492868/182136322-40345731-3688-4031-9452-75307f47dbf9.png)

With IDM and without proxy
1: 60kb/s
![1b6861ca291199f0f0628977567459d](https://user-images.githubusercontent.com/97492868/182136725-4e006a39-1937-4d75-8544-0d470628bf1c.png)
2:8Mb/s
![f3e145810e3ec164f49a261c60d5cc6](https://user-images.githubusercontent.com/97492868/182136738-f1c4b2a4-ea3a-4af2-952b-c9d0f6a94ca8.png)

**Comment by ivankravets** [comment]
PlatformIO is open source project and is fully controlled by our community. There are no espionage components presented in russian or government-related software. Please close all these 3rd party tools, turn off the proxy and use your legal internet provider by a Chinese company. Now, open PlatformIO CLI again and change the directory to the ESP32-based project (`cd my/projectdir`). 

1. Please remove `%USERPROFILE%/.platformio/packages` directory
2. In PlatformIO Core CLI where you changed the folder to the PlatformIO project, type `pio pkg install`.

Does it download fast?

**Comment by zeeeeeeeeeeeoo** [comment]
> PlatformIO is open source project and is fully controlled by our community. There are no espionage components presented in russian or government-related software. Please close all these 3rd party tools, turn off the proxy and use your legal internet provider by a Chinese company. Now, open PlatformIO CLI again and change the directory to the ESP32-based project (`cd my/projectdir`).
> 
> 1. Please remove `%USERPROFILE%/.platformio/packages` directory
> 2. In PlatformIO Core CLI where you changed the folder to the PlatformIO project, type `pio pkg install`.
> 
> Does it download fast?

it seems has no response without a proxy and says "error" a few minutes later 
![ebecba4ce9fe993a2a8a7e977dd2628](https://user-images.githubusercontent.com/97492868/182139452-017f9fd0-ee2f-4177-a887-6d4a6c44c2b6.png)

**Comment by ivankravets** [comment]
Did you override proxy settings in VSCode? Or, set the global HTTP_PROXY environment variable? We can try without VSCode using native `cmd.exe` (Terminal), please close VSCode

```
cd C:/Users/ZE
.platformio/penv/Scripts/activate
cd Documents/PlatformIO/1
pio pkg install
```

Does it work now?

**Comment by zeeeeeeeeeeeoo** [comment]
it very slow

![6c2d9670cdaf679b13e61d3406258d0](https://user-images.githubusercontent.com/97492868/182141706-663c83ed-d42c-44c5-8ead-69b9cb31560d.png)

**Comment by zeeeeeeeeeeeoo** [comment]
> Did you override proxy settings in VSCode? Or, set the global HTTP_PROXY environment variable? We can try without VSCode using native `cmd.exe` (Terminal), please close VSCode
> 
> ```
> cd C:/Users/ZE
> .platformio/penv/Scripts/activate
> cd Documents/PlatformIO/1
> pio pkg install
> ```
> 
> Does it work now?

it's very slow and stuck in 0%

![b61c528976744b527003ea7cd6f0c45](https://user-images.githubusercontent.com/97492868/182141942-1a37dff4-fcd4-4a9a-8726-d8cef0a72a0f.png)

**Comment by ivankravets** [comment]
Sorry, crazy hard to help here. You provide absolutely different results :( 

Do you mean that https://dl.registry.ns2.platformio.org/tools/cb/36/aefbf6f69f5e27302916f0a1d13c03da57946e5b251be009f7cd93179d41/framework-arduinoespressif32-3.20004.0.tar.gz still downloads well from your browser without any proxies, etc?

----

Maybe, the API is also fully blocked. Could you try the following links?

1. https://api.registry.platformio.org/v3/packages/platformio/tool/framework-arduinoespressif32?sid=4a8a9fc31dc15a4b87bb145b05db3ae0bf2333e4
2. https://api.registry.platformio.org/v3/packages/platformio/tool/framework-arduinoespressif32

The (1) MUST fail (400 error), and the second MUST be OK.

**Comment by zeeeeeeeeeeeoo** [comment]
> Sorry, crazy hard to help here. You provide absolutely different results :(
> 
> Do you mean that https://dl.registry.ns2.platformio.org/tools/cb/36/aefbf6f69f5e27302916f0a1d13c03da57946e5b251be009f7cd93179d41/framework-arduinoespressif32-3.20004.0.tar.gz still downloads well from your browser without any proxies, etc?
> 
> Maybe, the API is also fully blocked. Could you try the following links?
> 
> 1. https://api.registry.platformio.org/v3/packages/platformio/tool/framework-arduinoespressif32?sid=4a8a9fc31dc15a4b87bb145b05db3ae0bf2333e4
> 2. https://api.registry.platformio.org/v3/packages/platformio/tool/framework-arduinoespressif32
> 
> The (1) MUST fail (400 error), and the second MUST be OK.

(1)
![4192cc05a7d254db5a0e8c968d45091](https://user-images.githubusercontent.com/97492868/182144508-f256a6de-a490-4553-9cfb-4b1f89b2b6fa.png)
(2)
![0c4113ec93b80e8fbc25a6e9aed55c0](https://user-images.githubusercontent.com/97492868/182144520-b3673106-4390-461c-942d-b43ed0f0cbb7.png)

I am not very sure about what does the code excatly mean.
 it seems both （1） and （2） don't work without or with proxy.
and former link still download well.

**Comment by ivankravets** [comment]
I see the root of the problem. Your IP points to Los Angeles, USA. Please remove ALL proxy settings. You still serve through the USA. As result, PlatformIO uses one of the PlatformIO's US mirrors.

**Comment by zeeeeeeeeeeeoo** [comment]
> I see the root of the problem. Your IP points to Los Angeles, USA. Please remove ALL proxy settings. You still serve through the USA. As result, PlatformIO uses one of the PlatformIO's US mirrors.

I removed all my proxy settings , and ensured my IP address stay in China.
now there is a little improvement,but the download speed is still unsatisfactory

![fa1428c50cad02163ee2842aa191bbd](https://user-images.githubusercontent.com/97492868/182202786-53e53d11-8a02-4113-adba-15e155bd9c32.png)


Whatever, thanks for solving my urgent need , I can  creat a ESP32 project successfully now.

**Comment by ivankravets** [comment]
I've just prepared for you a special version of PlatformIO Core that will print the URL of a mirror.  How to switch to that special version?

1. Please repeat the steps mentioned in this comment https://github.com/platformio/platformio-core-installer/issues/2325#issuecomment-1201099511
2. Before running `pio pkg install`, run `pip install -U https://github.com/platformio/platformio-core/archive/refs/heads/feature/test-mirror.zip`
3. Remove some installed packages  from `~/.platformio/packages` to check the speed
4. Run `pio pkg install`

Please share here the output of `pio pkg install`.

**Comment by zeeeeeeeeeeeoo** [comment]
> I've just prepared for you a special version of PlatformIO Core that will print the URL of a mirror. How to switch to that special version?
> 
> 1. Please repeat the steps mentioned in this comment [Installation Manager #2325 (comment)](https://github.com/platformio/platformio-core-installer/issues/2325#issuecomment-1201089752)
> 2. Before running `pio pkg install`, run `pip install -U https://github.com/platformio/platformio-core/archive/refs/heads/feature/test-mirror.zip`
> 3. Remove some installed packages  from `~/.platformio/packages` to check the speed
> 4. Run `pio pkg install`
> 
> Please share here the output of `pio pkg install`.

![a1842bb66177bdad46666ec3511f46a](https://user-images.githubusercontent.com/97492868/182210575-89970c7a-ed73-4642-8aa9-cc9d4fc417ac.png)
Downloading from https://dl.registry.ns2.platformio.org/tools/c1/f9/7fce33658c3efb1f2396581eac9569e693949038b99d692dba51768afbe8/toolchain-xtensa32-windows-2.50200.97.tar.gz

**Comment by ivankravets** [comment]
Do you experience the same slow speed when opening the URL above in your browser?

**Comment by zeeeeeeeeeeeoo** [comment]
> Do you experience the same slow speed when opening the URL above in your browser?
![c4c9e91fac0594bf576a6dd424e06eb](https://user-images.githubusercontent.com/97492868/182212366-34c8f0fb-a4fb-40a0-97ad-38432a678745.png)
yes

**Comment by ivankravets** [comment]
Sorry for the delay. Does https://hk03.layerstack.com/100MB.test have good downloading speed?

**Comment by zeeeeeeeeeeeoo** [comment]
> Sorry for the delay. Does https://hk03.layerstack.com/100MB.test have good downloading speed?

yes it works well
![d68bec0f2ee34d522b4e327c7d26dc6](https://user-images.githubusercontent.com/97492868/182519501-acdf0d0c-0f1a-481c-9364-0ac97684214f.png)
