### ISSUE TITLE
Official installer looks like typical malware

### ISSUE THREAD

**Issue by gudvinr** [platformio/platformio-core-installer#2473]
[Installer script](https://github.com/platformio/platformio-core-installer/blob/develop/get-platformio.py) that is recommended installation metod for pio-core, looks like typical malware:
* it contains obfuscated binary payload
* extracts _something_
* installs extracted content on your system

It is not how well-behaving software should present and install itself. `get-platformio.py` should not hide what it does and what it uses and make it hard for user to do sanity check.

No one is safe against malicious attacks and when software uses malware-like behaviour to install itself, it is prone to abuse that can go unnoticed.

**Comment by gudvinr** [comment]
It still looks like malicious script downloading something shady encoded as base64. There's nothing more you can add to that.

**Comment by LunarEclipse363** [comment]
This is still an issue.

**Comment by gudvinr** [comment]
Given that https://copy.fail/ exists for a while it's really unsafe to run some random scripts. Stuff like this should not be buried under the pile of auto-reported issues
