### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by TheFve** [platformio/platformio-core-installer#2906]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.77.3
  PIO IDE: v3.1.1
  System: Linux, 5.19.0-41-generic, x64

  %23 Exception
  ```
  Error:     ERROR: Command errored out with exit status 1:
     command: /home/knud/.platformio/penv/bin/python -c 'import sys, setuptools, tokenize

**Comment by ivankravets** [comment]
Have you resolved this issue?
