### ISSUE TITLE
installs but after restart not installed

### ISSUE THREAD

**Issue by ktmer02** [platformio/platformio-core-installer#2947]
Hey guys, so im trying to install PlatformIO.
The first issue is that when i try to install it it says "python not installed" but it is installed so i put in the path to python.exe.
Then it installs and says restart Visual Studios Code, after doing that it trys to install again and again says "python not installed"
Can someone please help me out with this.

Best,
David

**Comment by ivankravets** [comment]
What is your OS?

**Comment by ktmer02** [comment]
> 

Windows 10

**Comment by ivankravets** [comment]
Do you use any espionage software("antivirus")?

**Comment by ivankravets** [comment]
Please re-test with the pre-release version. Navigate to the PlatformIO IDE extension in the VSCode and "Switch to the Pre-Release". Does it work now?
<img width="1125" alt="Screenshot 2023-06-02 at 13 16 00" src="https://github.com/platformio/platformio-vscode-ide/assets/1760209/ec0157fd-147c-4117-96bc-4e73e74c2e85">
