### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by xinrag** [platformio/platformio-core-installer#3016]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.79.2
  PIO IDE: v3.2.0
  System: Linux, 5.14.21-150500.52-default, x64

  %23 Exception
  ```
  Error: ERROR: Could not find a version that satisfies the requirement tabulate==0.9.* (from platformio) (from versions: 0.3, 0.4.2, 0.4.3, 0.4.4, 0.5, 0.5.1, 0.6, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6b0, 0.7.6rc0, 0.7.7, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10)
ERROR: No matching distribution found for tabulate==0.9.* (from platformio)
WARNING: You are using pip version 20.0.2

**Comment by ivankravets** [comment]
It looks like you use an espionage PyPi registry that does not have all packages. Please use the official PyPi registry.
