### ISSUE TITLE
Issue persists after doing what is said.

### ISSUE THREAD

**Issue by Clememovil** [platformio/platformio-core-installer#3024]
Hello, i still have the issue after i did that. Dont know what to do.

Error: Could not start PIO Home server: Timeout error at Timeout._onTimeout (/root/.vscode-server/extensions/platformio.platformio-ide-3.3.0-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:10588) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)...

**Comment by ivankravets** [comment]
Have you resolved this issue?
