### ISSUE TITLE
I encountered this error while installing the  platform IO in VS Code. for what?

### ISSUE THREAD

**Issue by ErfanHemati** [platformio/platformio-core-installer#3034]
Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues -> Installer version: 1.2.0 Platform: Windows-10 Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] Python path: ...

**Comment by ivankravets** [comment]
Please remove `~/.platformio` folder and restart VSCode.
