### ISSUE TITLE
Error: Compatible PlatformIO Core not found.

### ISSUE THREAD

**Issue by chrisart1511** [platformio/platformio-core-installer#3062]
Hello, I am fairly new to VSCode and am trying to install Platformio. Unfortunately, frustratingly, I continuously get the following error message. I have already uninstalled and deleted everything several times and can't get any further. I'm running OSX 13.4 (22F66):

Error: Compatible PlatformIO Core not found. Reason: Could not run `/Users/XX/.platformio/penv/bin/platformio --help`. Error: Traceback (most recent call last): File "/Users/XX/.platformio/penv/bin/platformio", line 5, in <module> from platformio.__main__ import main File "/Users/XX/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py", line 21, in <module> from platformio import __version__, exception, maintenance File "/Users/XX/.platformio/penv/lib/python3.7/site-packages/platformio/maintenance.py", line 22, in <module> from platformio import __version__, app, exception, fs, telemetry File "/...

**Comment by ivankravets** [comment]
Please remove `/Users/XX/.platformio` folder and restart VSCode.
