### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ffhfggc** [platformio/platformio-core-installer#3096]
%23 Description of problem  Leave a comment...  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue   %23 Configuration  VSCode: 1.83.1  PIO IDE: v2.4.3  System: Windows_NT, 10.0.19045, x64  %23 Exception  ```  Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.	at u.value (c:\Users\小新\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\platformio-node-helpers\dist\index.js:1:783624)	at S.install (c:\Users\小新\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:4381)	at c:\Users\小新\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:28144	at k.d (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:123:46049)	at k.withProgress (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:123:45912)	at Object.withProgress (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:31573)	at Object.startInstaller (c:\Users\小新\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:27559)	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)	at async Object.activate (c:\Users\小新\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:23007)  ```

**Comment by ivankravets** [comment]
Please update VSCode and PlatformIO IDE extension to the latest version https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
