### ISSUE TITLE
Trouble installing get-platformio.py

### ISSUE THREAD

**Issue by jrive87** [platformio/platformio-core-installer#3134]
I have two issues while installing get-platformio.py:  1) it was failing stating the reason due to an incompatible version of Python, even though it was using version 3.9.15.   i then tried installing version 3.12, but no matter what i did (including changing the python default interpreter path in the workspace and relaunching VS), but it keeps trying to use version 3.9.15 .  So, the first issue is that the default interpreter path setting doesn't seem to work.

Then 2, I got the error below, after changing python default interpreter path in the workspace.  It still pointed to python version 3.9.15 as shown below, but now the error was different, prompting me to report the issue to the link provided.

> PS C:\Users\jeriv\OneDrive\Documents\PlatformIO\Projects\test2> python C:\users\jeriv\OneDrive\Downloads\get-platformio.py      
> Installer version: 1.2.1
> Platform: Windows-10
> Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:41:22) [MSC v.1929 64 bit (AMD64)]
> Python path: C:\Users\jeriv\anaconda3\envs\Scripts\python.exe
> Creating a virtual environment at C:\Users\jeriv\.platformio\penv
> C:\Users\jeriv\anaconda3\envs\Scripts\python.exe
> Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues

**Comment by ivankravets** [comment]
> anaconda3

But Anaconda is not supported by PlatformIO? PlatformIO IDE for VSCode comes with built-in Python 3.11. It should work.

Could you update VSCode + PlatformIO IDE extension to the latest version, remove `C:/Users/jeriv/.platformio` and restart VCode?
