### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by thermalhound** [platformio/platformio-core-installer#342]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.51.1
  PIO IDE: v2.2.1
  System: Linux, 5.4.0-53-generic, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "<frozen zipimport>", line 520, in _get_decompress_func
ModuleNotFoundError: No module named 'zlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 568, in _get_data
  File "<frozen zipimport>", line 523, in _get_decompress_func
zipimport.ZipImportError: can't decompress data

**Comment by ivankravets** [comment]
Broken Python. Please check that you have valid Python 3.6+ and restart VSCode.
