### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by scordd** [platformio/platformio-core-installer#347]
Error: Traceback (most recent call last): File "/Users/eah24sava/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 69, in main() File "/Users/eah24sava/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 61, in main bootstrap() File "/Users/eah24sava/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 47, in bootstrap pioinstaller.main.main() File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/pioinstaller/main.py", line 122, in main File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/click/core.py", line 829, in call File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/click/core.py", line 782, in main File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/click/core.py", line 1236, in invoke File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/click/core.py", line 1066, in invoke File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/click/core.py", line 610, in invoke File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/click/decorators.py", line 21, in new_func File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/pioinstaller/main.py", line 52, in cli File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/pioinstaller/core.py", line 72, in install_platformio_core File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/pioinstaller/penv.py", line 52, in create_core_penv File "/Users/eah24sava/.platformio/.cache/tmp/.piocore-installer-8dH2zB/tmpzspWix/pioinstaller.zip/pioinstaller/python.py", line 178, in find_compatible_pythons File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output process = Popen(stdout=PIPE, *popenargs, **kwargs) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in init errread, errwrite) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child raise child_exception OSError: [Errno 13] Permission denied -> Installer version: 0.3.5 Platform: Darwin-19.5.0 Python version: 2.7.16 (default, Apr 17 2020, 18:29:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- Python path: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python Creating a virtual environment at /Users/eah24sava/.platformio/penv

at /Users/eah24sava/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5004
at ChildProcess.s (/Users/eah24sava/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4900)
at ChildProcess.emit (events.js:194:13)
at maybeClose (internal/child_process.js:998:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

**Comment by ivankravets** [comment]
Please install the latest Python 3 as described in https://docs.platformio.org/en/latest/faq.html#install-python-interpreter and restart VSCode.
