### ISSUE TITLE
my pio do not show the boards list.

### ISSUE THREAD

**Issue by newbeast-simon** [platformio/platformio-core-installer#393]
It shows that I successfully installed the pio core, but when I run command "pio boards", it shows "fail to check for pio upgrades ", then I run the command again, It shows nothing. 
My system is win7, and I'm from China, and the net connection is not so good in my country, you know. 
![image](https://user-images.githubusercontent.com/59795546/102776590-f43c1d80-43c9-11eb-9984-e5790a5dfded.png)
![image](https://user-images.githubusercontent.com/59795546/102776635-0918b100-43ca-11eb-83dc-1a96f32c0b78.png)
Thank you!

**Comment by newbeast-simon** [comment]
![image](https://user-images.githubusercontent.com/59795546/102843356-fe9afd80-4443-11eb-8c97-000bd6ad6592.png)
When running command "pio update",it shows like this, and nothing else happend. There is no directory "lib" there at all.

**Comment by newbeast-simon** [comment]
My Clion installed pio plug.  When newing a pio project,   it shows like this and then have no response.
![image](https://user-images.githubusercontent.com/59795546/102849103-5ee46c00-4451-11eb-8973-5c765d8c80c8.png)

**Comment by newbeast-simon** [comment]
Anyone help?

**Comment by newbeast-simon** [comment]
I got some clue. My python environment is Anaconda, it seems that the pio-core-installer don't support Anaconda.
"pip install" is not allways work in my internet environment, on the contrary, "conda install" works well.

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
yes, we don't support anaconda. Please install the latest official Python 3 https://docs.platformio.org/en/latest/faq.html#install-python-interpreter and restart installer
