### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by clavilla** [platformio/platformio-core-installer#427]
Error: Traceback (most recent call last): File "C:\Users\crist.platformio.cache\tmp\get-platformio-0.3.5.py", line 69, in main() File "C:\Users\crist.platformio.cache\tmp\get-platformio-0.3.5.py", line 61, in main bootstrap() File "C:\Users\crist.platformio.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap pioinstaller.main.main() File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\pioinstaller_main__.py", line 122, in main File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie\tmp52mlk6hv\pioinstaller.zip\click\core.py", line 829, in call File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\click\core.py", line 782, in main File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\click\core.py", line 1259, in invoke File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\click\core.py", line 1259, in invoke File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\click\core.py", line 1066, in invoke File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\click\core.py", line 610, in invoke File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\click\decorators.py", line 21, in new_func File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\pioinstaller__main__.py", line 106, in core_check File "C:\Users\crist.platformio.cache\tmp.piocore-installer-qotwzie_\tmp52mlk6hv\pioinstaller.zip\pioinstaller\core.py", line 193, in check File "C:\Users\crist.platformio\python3\lib\subprocess.py", line 411, in check_output kwargs).stdout File "C:\Users\crist.platformio\python3\lib\subprocess.py", line 488, in run with Popen(*popenargs, kwargs) as process: File "C:\Users\crist.platformio\python3\lib\subprocess.py", line 800, in init restore_signals, start_new_session) File "C:\Users\crist.platformio\python3\lib\subprocess.py", line 1207, in _execute_child startupinfo) PermissionError: [WinError 5] Acceso denegado

**Comment by ivankravets** [comment]
Have you resolved this issue?
