### ISSUE TITLE
Error: Compatible PlatformIO Core not found

### ISSUE THREAD

**Issue by kfine100** [platformio/platformio-core-installer#429]
How to solve this complaint???

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Linux, 5.4.0-58-generic, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO installed using another platform `Linux-5.4.0-58-generic-x86_64-with-glibc2.29`. Your platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.10

	at /home/kevin/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/home/kevin/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
Please remove `~/.platformio/penv` folder and restart VSCode.

**Comment by kfine100** [comment]
Yes, removing penv does make the error go away.

Thanks

**Comment by kfine100** [comment]
While the above solutions work they are temporary. The error always comes back after a couple of weeks. I keep my Ubuntu 20.04 up to date and recently did one..........could this be related? Here is the error that is appearing again.

Kevin

Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO installed using another platform `Linux-5.4.0-65-generic-x86_64-with-glibc2.10`. Your platform: Linux-5.4.0-65-generic-x86_64-with-glibc2.29

	at /home/kevin/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/home/kevin/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)...

**Comment by ivankravets** [comment]
Where do you see this error?

**Comment by kfine100** [comment]
Hi Ivan

When I start VS Code, the following installation window pops up. This one finishes with "PlatformIO IDE installed successfully" but I sometimes instead get the above error.

![image](https://user-images.githubusercontent.com/8997519/106150166-56cbca80-617b-11eb-9a73-1e23132b6b32.png)

**Comment by ivankravets** [comment]
This is correct. You do OS updates, it changes system libraries, we need to recreate virtual environemnt.

**Comment by kfine100** [comment]
So really there is no error? Looking at the past prints there is an evolution of libraries:

Linux-5.4.0-58-generic-x86_64-with-glibc2.10
Linux-5.4.0-65-generic-x86_64-with-glibc2.10
Linux-5.4.0-65-generic-x86_64-with-glibc2.29

due to Ubuntu updates. The PIO installation is just adapting to the new ones.

I also occasionally get an error about multiple installed platforms. Maybe this is because one of the previous installations sticks around. I suppose I can always clean that out by removing .penv?

Kevin

**Comment by ivankravets** [comment]
Thanks, I reopened this issue. We will think of a better solution.

**Comment by kfine100** [comment]
You guys are doing a great job. If others responded as quick as you, the world would be a better place!

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
