### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by NickelWenzel** [platformio/platformio-core-installer#445]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Linux, 5.4.0-60-generic, x64

  %23 Exception
  ```
  Error:     ERROR: Command errored out with exit status 1:
     command: /home/nickel/.platformio/penv/bin/python -c 'import sys, setuptools, tokenize

**Comment by ivankravets** [comment]
Have you resolved this issue?
