### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by johnsw87** [platformio/platformio-core-installer#52]
# Description of problem Leave a comment... BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN - https://github.com/platformio/platformio-vscode-ide/issues?q=is:issue  # Configuration VSCode: 1.47.1 PIO IDE: v2.0.0-beta.5 System: Windows_NT, 10.0.18363, x64 # Exception ``` Error: Traceback (most recent call last): File "C:\Users\john\.platformio\.cache\get-platformio-0.3.2.py", line 53, in <module> main() File "C:\Users\john\.platformio\.cache\get-platformio-0.3.2.py", line 46, in main bootstrap() File "C:\Users\john\.platformio\.cache\get-platformio-0.3.2.py", line 32, in bootstrap pioinstaller.__main__.main() File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\pioinstaller\__main__.py", line 122, in main File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\click\core.py", line 829, in __call__ File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\click\core.py", line 782, in main File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\click\core.py", line 1236, in invoke File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\click\core.py", line 1066, in invoke File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\click\core.py", line 610, in invoke File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\click\decorators.py", line 21, in new_func File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\pioinstaller\__main__.py", line 52, in cli File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\pioinstaller\penv.py", line 52, in create_core_penv File "C:\Users\john\AppData\Local\Temp\tmpe6vowlds\pioinstaller.zip\pioinstaller\python.py", line 159, in find_compatible_pythons File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 411, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 489, in run with Popen(*popenargs, **kwargs) as process: File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 854, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, PermissionError: [WinError 5] Access is denied Error: spawn C:\Users\john\AppData\Local\Microsoft\WindowsApps\python.exe ENOENT -> Installer version: 0.3.2 Platform: Windows-10 Python version: 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)] Python path: C:\Users\john\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe Creating a virtual environment at C:\Users\john\.platformio\penv at c:\Users\john\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\dist\index.js:1:4882 at c (c:\Users\john\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\dist\index.js:1:4778) at ChildProcess.<anonymous> (c:\Users\john\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\dist\index.js:1:4625) at ChildProcess.emit (events.js:203:13) at ChildProcess.cp.emit (c:\Users\john\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\node_modules\cross-spawn\lib\enoent.js:30:37) at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) ```

**Comment by ivankravets** [comment]
How did you resovle it?
