### ISSUE TITLE
Problème installation platformIO

### ISSUE THREAD

**Issue by wintternox** [platformio/platformio-core-installer#553]
Bonjour à tous, 
J'ai un soucis, je n'arrive pas à installer platformIO sur VS code. Quand je lance l'installation depuis VS code j'ai ce message d'erreur: 
![problème platformio](https://user-images.githubusercontent.com/80101864/110107315-04e61800-7dab-11eb-94ae-724bf7c670a1.jpg)
pouvez vous m'aidez??  Je suis trop dans la galère sinon 

merci par avance ;)

**Comment by dsferruzza** [comment]
Même problème pour moi ; j'ai rollback sur la version précédente de l'extension (Ctrl + Shift + P, puis `Extensions: Install Specific Version of Extension`) en attendant

**Comment by kergaradec** [comment]
J'ai également le même soucis et le retour en version précédente n'a eu aucun effet, donc mon problème persiste.

**Comment by ouistiti91** [comment]
Même problème, résolu en installant python avant d'installer platformIO. Dans mon cas, je suis passé par microsoft store pour installer python 3.9.
