### ISSUE TITLE
Platformio: Flash Tasmota sur ESP32

### ISSUE THREAD

**Issue by PPHIL972** [platformio/platformio-core-installer#643]
Bonjour, je voudrais savoir si le flash de TASMOTA sur ESP32 est possible, si oui comment ? J'ai essayé mais cela ne fonctionne pas, il y a toujours un message d'erreur issu du fichier platformio.ini
Merci de votre aide.

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
