### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by tomacraft1756** [platformio/platformio-core-installer#922]
Error: Traceback (most recent call last): File "C:\Users\User.platformio.cache\tmp\get-platformio-0.3.5.py", line 69, in main() File "C:\Users\User.platformio.cache\tmp\get-platformio-0.3.5.py", line 61, in main bootstrap() File "C:\Users\User.platformio.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap pioinstaller.main.main() File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\pioinstaller_main__.py", line 122, in main File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r\tmp9jcuwkcg\pioinstaller.zip\click\core.py", line 829, in call File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\click\core.py", line 782, in main File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\click\core.py", line 1259, in invoke File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\click\core.py", line 1259, in invoke File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\click\core.py", line 1066, in invoke File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\click\core.py", line 610, in invoke File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\click\decorators.py", line 21, in new_func File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\pioinstaller__main__.py", line 103, in core_check File "C:\Users\User.platformio.cache\tmp.piocore-installer-1pvt51r_\tmp9jcuwkcg\pioinstaller.zip\pioinstaller\core.py", line 193, in check File "C:\Users\User.platformio\python3\lib\subprocess.py", line 424, in check_output return run(popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:\Users\User.platformio\python3\lib\subprocess.py", line 505, in run with Popen(popenargs, **kwargs) as process: File "C:\Users\User.platformio\python3\lib\subprocess.py", line 951, in init self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\User.platformio\python3\lib\subprocess.py", line 1420, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, PermissionError: [WinError 5] �׼����� �źεǾ����ϴ�
------------------------------------------------------------------------------------------
at C:\Users\User\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5004
at ChildProcess.s (C:\Users\User\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4900)
at ChildProcess.emit (events.js:223:5)
at ChildProcess.cp.emit (C:\Users\User\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by ivankravets** [comment]
Please update the PlatformIO IDE extension in the VSCode to the latest version. The bug is fixed.
