### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by kaa1066** [platformio/platformio-core-installer#969]
Error: Traceback (most recent call last): File "C:\Users\kim.platformio.cache\tmp\get-platformio-0.3.5.py", line 69, in main() File "C:\Users\kim.platformio.cache\tmp\get-platformio-0.3.5.py", line 61, in main bootstrap() File "C:\Users\kim.platformio.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap pioinstaller.main.main() File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\pioinstaller__main__.py", line 122, in main File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\click\core.py", line 829, in call File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\click\core.py", line 782, in main File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\click\core.py", line 1236, in invoke File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\click\core.py", line 1066, in invoke File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\click\core.py", line 610, in invoke File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\click\decorators.py", line 21, in new_func File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\pioinstaller__main__.py", line 52, in cli File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\pioinstaller\penv.py", line 75, in create_core_penv File "C:\Users\kim.platformio.cache\tmp.piocore-installer-j37ft9_n\tmpzusesz_2\pioinstaller.zip\pioinstaller\penv.py", line 143, in add_state_info File "C:\Program Files\Inkscape\lib\python3.8\subprocess.py", line 411, in check_output return run(popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:\Program Files\Inkscape\lib\python3.8\subprocess.py", line 489, in run with Popen(popenargs, **kwargs) as process: File "C:\Program Files\Inkscape\lib\python3.8\subprocess.py", line 854, in init self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Program Files\Inkscape\lib\python3.8\subprocess.py", line 1307, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] Den angivne fil blev ikke fundet -> Installer version: 0.3.5 Platform: Windows-10 Python version: 3.8.7 (default, Jan 31 2021, 16:39:53) [GCC 10.2.0 64 bit (AMD64)] Python path: C:\Program Files\Inkscape\bin\python.exe Creating a virtual environment at C:\Users\kim.platformio\penv

at C:\Users\kim\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5004
at ChildProcess.s (C:\Users\kim\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4900)
at ChildProcess.emit (events.js:223:5)
at ChildProcess.cp.emit (C:\Users\kim\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by ivankravets** [comment]
Please update the PlatformIO IDE extension in the VSCode to the latest version. The bug is fixed.
